In [72]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor

In [73]:
df = pd.read_csv('train (1).csv')
df

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
0,14038,35,2.0,47.981561,29.442751,6.0,7,9.0,1969,0.089040,B,B,33,7976,5,NaN,0,11,B,184966.930730
1,15053,41,3.0,65.683640,40.049543,8.0,7,9.0,1978,0.000070,B,B,46,10309,1,240.0,1,16,B,300009.450063
2,4765,53,2.0,44.947953,29.197612,0.0,8,12.0,1968,0.049637,B,B,34,7759,0,229.0,1,3,B,220925.908524
3,5809,58,2.0,53.352981,52.731512,9.0,8,17.0,1977,0.437885,B,B,23,5735,3,1084.0,0,5,B,175616.227217
4,10783,99,1.0,39.649192,23.776169,7.0,11,12.0,1976,0.012339,B,B,35,5776,1,2078.0,2,4,B,150226.531644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,77,32,2.0,50.401785,30.476203,5.0,6,5.0,1968,0.135650,B,B,46,7960,6,350.0,3,11,B,196684.316040
9996,6159,18,1.0,41.521546,20.539216,9.0,13,13.0,2000,0.000000,B,B,30,5562,0,NaN,0,5,A,189050.289571
9997,5123,27,1.0,47.939008,NaN,1.0,12,16.0,2015,0.072158,B,B,2,629,1,NaN,0,0,A,159143.805370
9998,5400,75,2.0,43.602562,33.840147,8.0,1,5.0,1961,0.307467,B,A,30,5048,9,325.0,2,5,B,181595.339808
9999,6306,128,1.0,38.666645,21.157874,8.0,7,17.0,1990,0.000000,B,B,27,4798,0,30.0,2,8,B,218714.077615

In [74]:
df.describe()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Price
count,10000.00000,10000.000000,10000.000000,10000.000000,7887.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,5202.000000,10000.000000,10000.000000,10000.000000
mean,8383.40770,50.400800,1.890500,56.315775,37.199645,6.273300,8.526700,12.609400,3.990166e+03,0.118858,24.687000,5352.157400,8.039200,1142.904460,1.319500,4.231300,214138.857399
std,4859.01902,43.587592,0.839512,21.058732,86.241209,28.560917,5.241148,6.775974,2.005003e+05,0.119025,17.532614,4006.799803,23.831875,1021.517264,1.493601,4.806341,92872.293865
min,0.00000,0.000000,0.000000,1.136859,0.370619,0.000000,1.000000,0.000000,1.910000e+03,0.000000,0.000000,168.000000,0.000000,0.000000,0.000000,0.000000,59174.778028
25%,4169.50000,20.000000,1.000000,41.774881,22.769832,1.000000,4.000000,9.000000,1.974000e+03,0.017647,6.000000,1564.000000,0.000000,350.000000,0.000000,1.000000,153872.633942
50%,8394.50000,36.000000,2.000000,52.513310,32.781260,6.000000,7.000000,13.000000,1.977000e+03,0.075424,25.000000,5285.000000,2.000000,900.000000,1.000000,3.000000,192269.644879
75%,12592.50000,75.000000,2.000000,65.900625,45.128803,9.000000,12.000000,17.000000,2.001000e+03,0.195781,36.000000,7227.000000,5.000000,1548.000000,2.000000,6.000000,249135.462171
max,16798.00000,209.000000,19.000000,641.065193,7480.592129,2014.000000,42.000000,117.000000,2.005201e+07,0.521867,74.000000,19083.000000,141.000000,4849.000000,6.000000,23.000000,633233.466570

Имеем не корректные даты постройки

In [ ]:
df.loc[df['HouseYear'] > 2020, 'HouseYear'] = df['HouseYear'].median()

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             10000 non-null  int64
 1   DistrictId     10000 non-null  int64
 2   Rooms          10000 non-null  float64
 3   Square         10000 non-null  float64
 4   LifeSquare     7887 non-null   float64
 5   KitchenSquare  10000 non-null  float64
 6   Floor          10000 non-null  int64
 7   HouseFloor     10000 non-null  float64
 8   HouseYear      10000 non-null  int64
 9   Ecology_1      10000 non-null  float64
 10  Ecology_2      10000 non-null  object
 11  Ecology_3      10000 non-null  object
 12  Social_1       10000 non-null  int64
 13  Social_2       10000 non-null  int64
 14  Social_3       10000 non-null  int64
 15  Healthcare_1   5202 non-null   float64
 16  Helthcare_2    10000 non-null  int64
 17  Shops_1        10000 non-null  int64
 18  Shops_2        10000 non-null  object
 19  Price          10000 non-null  float64
dtypes: float64(8), int64(9), object(3)
memory usage: 1.5+ MB

Healthcare_1 и LifeSquare имеют много пропусков, удалим эти столбцы

In [76]:
target = df['Price']
df.drop(['Id', 'Healthcare_1', 'LifeSquare', 'Price'], axis=1, inplace=True)

In [77]:
df = pd.get_dummies(df)

Модель линейной регрессии дало результаты по метрике r2 не более 0,4. Будем использовать случайный лес

In [84]:
rgr = GridSearchCV(
    estimator= RandomForestRegressor(),
    scoring='r2',
    cv=5,
    param_grid={
        'n_estimators' : [100, 150, 200],
        'max_depth' : [9, 10, 11],
        'max_features' : np.arange(4,10)
    }
)

In [85]:
%%time
X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.3, random_state=27)
rgr.fit(X_train, y_train)
r2_score(y_test, rgr.predict(X_test)), r2_score(y_train, rgr.predict(X_train))

CPU times: total: 3min 54s
Wall time: 4min

(0.7403109342660499, 0.8702966827048437)

In [86]:
cv_results = pd.DataFrame(rgr.cv_results_)
cv_results.sort_values('rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
44,1.123258,0.022103,0.040592,0.000489,11,6,200,"{'max_depth': 11, 'max_features': 6, 'n_estima...",0.711363,0.683652,0.723870,0.727285,0.756226,0.720479,0.023559,1
40,0.739129,0.005224,0.031003,0.000009,11,5,150,"{'max_depth': 11, 'max_features': 5, 'n_estima...",0.712242,0.679433,0.725066,0.726050,0.759133,0.720385,0.025686,2
41,0.981802,0.009019,0.040595,0.000496,11,5,200,"{'max_depth': 11, 'max_features': 5, 'n_estima...",0.713649,0.681447,0.721293,0.728272,0.756792,0.720291,0.024290,3
50,1.390272,0.021386,0.040188,0.000399,11,8,200,"{'max_depth': 11, 'max_features': 8, 'n_estima...",0.708599,0.679335,0.721621,0.733487,0.757903,0.720189,0.026094,4
45,0.623352,0.001890,0.021594,0.000491,11,7,100,"{'max_depth': 11, 'max_features': 7, 'n_estima...",0.713148,0.677320,0.719964,0.730968,0.758720,0.720024,0.026412,5
42,0.557701,0.002158,0.021190,0.000402,11,6,100,"{'max_depth': 11, 'max_features': 6, 'n_estima...",0.711741,0.674109,0.721788,0.733300,0.758981,0.719984,0.027834,6
46,0.933809,0.001510,0.031196,0.000408,11,7,150,"{'max_depth': 11, 'max_features': 7, 'n_estima...",0.711542,0.676441,0.724002,0.729975,0.755626,0.719517,0.025894,7
51,0.755836,0.002248,0.020982,0.000008,11,9,100,"{'max_depth': 11, 'max_features': 9, 'n_estima...",0.709788,0.678218,0.724191,0.731654,0.753537,0.719478,0.025007,8
53,1.510089,0.007146,0.040587,0.000495,11,9,200,"{'max_depth': 11, 'max_features': 9, 'n_estima...",0.708538,0.677554,0.726565,0.728261,0.756321,0.719448,0.025931,9
39,0.492104,0.002017,0.021200,0.000396,11,5,100,"{'max_depth': 11, 'max_features': 5, 'n_estima...",0.711164,0.680593,0.720317,0.728846,0.756007,0.719385,0.024511,10
43,0.838516,0.003060,0.030984,0.000007,11,6,150,"{'max_depth': 11, 'max_features': 6, 'n_estima...",0.711394,0.681061,0.714872,0.728764,0.759939,0.719206,0.025633,11
52,1.138004,0.003778,0.030791,0.000401,11,9,150,"{'max_depth': 11, 'max_features': 9, 'n_estima...",0.709734,0.674655,0.723040,0.734530,0.753664,0.719125,0.026500,12
49,1.030687,0.001411,0.031196,0.000752,11,8,150,"{'max_depth': 11, 'max_features': 8, 'n_estima...",0.709894,0.678361,0.721428,0.728188,0.756257,0.718826,0.025348,13
47,1.244851,0.007899,0.040395,0.000495,11,7,200,"{'max_depth': 11, 'max_features': 7, 'n_estima...",0.709151,0.676979,0.724652,0.727657,0.754831,0.718654,0.025506,14
48,0.691560,0.003424,0.021004,0.000012,11,8,100,"{'max_depth': 11, 'max_features': 8, 'n_estima...",0.709901,0.677213,0.721256,0.729980,0.754456,0.718561,0.025341,15
38,0.853394,0.007984,0.040584,0.000801,11,4,200,"{'max_depth': 11, 'max_features': 4, 'n_estima...",0.708644,0.679141,0.720156,0.728123,0.756682,0.718549,0.025296,16
37,0.638527,0.002628,0.037191,0.012900,11,4,150,"{'max_depth': 11, 'max_features': 4, 'n_estima...",0.709314,0.678977,0.721323,0.722782,0.756276,0.717734,0.024887,17
28,0.871901,0.013412,0.029391,0.001025,10,7,150,"{'max_depth': 10, 'max_features': 7, 'n_estima...",0.708042,0.676589,0.721837,0.725975,0.752352,0.716959,0.024767,18
36,0.422919,0.001400,0.021398,0.000485,11,4,100,"{'max_depth': 11, 'max_features': 4, 'n_estima...",0.709055,0.681172,0.718801,0.724530,0.749718,0.716655,0.022255,19
34,1.124621,0.026043,0.030390,0.001496,10,9,150,"{'max_depth': 10, 'max_features': 9, 'n_estima...",0.709507,0.675757,0.719195,0.727812,0.750378,0.716530,0.024462,20
29,1.218918,0.124262,0.041196,0.005030,10,7,200,"{'max_depth': 10, 'max_features': 7, 'n_estima...",0.709225,0.675048,0.717419,0.725619,0.751718,0.715806,0.024872,21
31,1.090696,0.073591,0.035190,0.005496,10,8,150,"{'max_depth': 10, 'max_features': 8, 'n_estima...",0.707987,0.675315,0.718350,0.728134,0.748586,0.715674,0.024222,22
24,0.541582,0.028082,0.019994,0.000894,10,6,100,"{'max_depth': 10, 'max_features': 6, 'n_estima...",0.706452,0.676341,0.717934,0.724444,0.750205,0.715075,0.024103,23
27,0.586959,0.006907,0.020783,0.000742,10,7,100,"{'max_depth': 10, 'max_features': 7, 'n_estima...",0.707475,0.672871,0.720632,0.722809,0.751508,0.715059,0.025522,24
22,0.669667,0.002228,0.028793,0.000395,10,5,150,"{'max_depth': 10, 'max_features': 5, 'n_estima...",0.704628,0.675425,0.717069,0.723717,0.754154,0.714999,0.025640,25
35,1.399130,0.016272,0.037985,0.000012,10,9,200,"{'max_depth': 10, 'max_features': 9, 'n_estima...",0.705001,0.670312,0.719521,0.728811,0.750847,0.714898,0.026807,26
32,1.334830,0.030264,0.038693,0.001399,10,8,200,"{'max_depth': 10, 'max_features': 8, 'n_estima...",0.705541,0.676228,0.716455,0.725188,0.750983,0.714879,0.024468,27
23,0.903218,0.013734,0.037791,0.000402,10,5,200,"{'max_depth': 10, 'max_features': 5, 'n_estima...",0.708787,0.675953,0.714816,0.723007,0.751468,0.714806,0.024319,28
26,1.024109,0.015322,0.037996,0.000639,10,6,200,"{'max_depth': 10, 'max_features': 6, 'n_estima...",0.705754,0.675947,0.716546,0.721995,0.752033,0.714455,0.024625,29
21,0.447021,0.001217,0.019794,0.000394,10,5,100,"{'max_depth': 10, 'max_features': 5, 'n_estima...",0.704985,0.672227,0.717940,0.721143,0.753388,0.713937,0.026246,30
25,0.769381,0.018083,0.028993,0.000636,10,6,150,"{'max_depth': 10, 'max_features': 6, 'n_estima...",0.703611,0.677615,0.713442,0.720922,0.752818,0.713681,0.024439,31
30,0.726663,0.070037,0.028594,0.011818,10,8,100,"{'max_depth': 10, 'max_features': 8, 'n_estima...",0.703501,0.675279,0.717801,0.724494,0.746152,0.713445,0.023522,32
20,0.770850,0.002729,0.037299,0.000401,10,4,200,"{'max_depth': 10, 'max_features': 4, 'n_estima...",0.705895,0.676446,0.715363,0.720580,0.748417,0.713340,0.023253,33
19,0.578672,0.002688,0.028587,0.000484,10,4,150,"{'max_depth': 10, 'max_features': 4, 'n_estima...",0.707714,0.677416,0.714137,0.715868,0.748045,0.712636,0.022500,34
33,0.719732,0.015039,0.020196,0.000747,10,9,100,"{'max_depth': 10, 'max_features': 9, 'n_estima...",0.699141,0.671686,0.713340,0.727855,0.750348,0.712474,0.026507,35
18,0.388408,0.002558,0.019596,0.000492,10,4,100,"{'max_depth': 10, 'max_features': 4, 'n_estima...",0.700838,0.672662,0.710553,0.719426,0.747898,0.710276,0.024507,36
15,0.632413,0.004018,0.018003,0.000011,9,9,100,"{'max_depth': 9, 'max_features': 9, 'n_estimat...",0.700011,0.672217,0.707065,0.719874,0.744398,0.708713,0.023700,37
13,0.965589,0.086385,0.027194,0.000399,9,8,150,"{'max_depth': 9, 'max_features': 8, 'n_estimat...",0.700337,0.670742,0.712585,0.716936,0.741443,0.708409,0.023089,38
10,0.880049,0.036818,0.028799,0.000750,9,7,150,"{'max_depth': 9, 'max_features': 7, 'n_estimat...",0.702694,0.670042,0.710525,0.715162,0.742335,0.708151,0.023261,39
17,1.268625,0.011434,0.035196,0.000748,9,9,200,"{'max_depth': 9, 'max_features': 9, 'n_estimat...",0.698854,0.669766,0.710582,0.717692,0.742708,0.707920,0.023878,40
11,1.125739,0.029951,0.037393,0.001023,9,7,200,"{'max_depth': 9, 'max_features': 7, 'n_estimat...",0.700742,0.667600,0.706860,0.716289,0.747327,0.707764,0.025695,41
16,0.957608,0.029900,0.026195,0.000750,9,9,150,"{'max_depth': 9, 'max_features': 9, 'n_estimat...",0.695679,0.670207,0.711244,0.718738,0.742885,0.707750,0.024177,42
8,1.096055,0.033830,0.039781,0.001606,9,6,200,"{'max_depth': 9, 'max_features': 6, 'n_estimat...",0.697738,0.671590,0.711022,0.715165,0.742475,0.707598,0.023148,43
14,1.156008,0.009094,0.034802,0.000399,9,8,200,"{'max_depth': 9, 'max_features': 8, 'n_estimat...",0.701066,0.666241,0.711164,0.716494,0.742567,0.707506,0.024770,44
12,0.661838,0.044381,0.021197,0.002040,9,8,100,"{'max_depth': 9, 'max_features': 8, 'n_estimat...",0.695404,0.666412,0.713992,0.716143,0.744898,0.707370,0.025884,45
9,0.586540,0.008481,0.020391,0.000795,9,7,100,"{'max_depth': 9, 'max_features': 7, 'n_estimat...",0.697899,0.671185,0.708849,0.715641,0.742356,0.707186,0.023210,46
7,0.764381,0.015888,0.033585,0.007807,9,6,150,"{'max_depth': 9, 'max_features': 6, 'n_estimat...",0.697871,0.668259,0.711800,0.714385,0.743178,0.707098,0.024374,47
6,0.517924,0.012158,0.020195,0.000399,9,6,100,"{'max_depth': 9, 'max_features': 6, 'n_estimat...",0.700644,0.669791,0.708329,0.713862,0.741876,0.706900,0.023195,48
3,0.642512,0.094774,0.024794,0.004443,9,5,100,"{'max_depth': 9, 'max_features': 5, 'n_estimat...",0.700127,0.672129,0.705236,0.716936,0.736989,0.706283,0.021269,49
5,0.915350,0.032457,0.040181,0.006080,9,5,200,"{'max_depth': 9, 'max_features': 5, 'n_estimat...",0.697642,0.668640,0.708554,0.712290,0.742292,0.705884,0.023785,50
4,0.796095,0.032640,0.032590,0.006216,9,5,150,"{'max_depth': 9, 'max_features': 5, 'n_estimat...",0.693690,0.667621,0.707150,0.714438,0.741904,0.704960,0.024416,51
1,0.683744,0.025274,0.032788,0.002318,9,4,150,"{'max_depth': 9, 'max_features': 4, 'n_estimat...",0.695144,0.666617,0.706802,0.706722,0.738146,0.702686,0.023015,52
2,0.906170,0.040970,0.039792,0.003482,9,4,200,"{'max_depth': 9, 'max_features': 4, 'n_estimat...",0.694297,0.666122,0.706745,0.708031,0.737030,0.702445,0.022942,53
0,0.414675,0.022672,0.021785,0.001839,9,4,100,"{'max_depth': 9, 'max_features': 4, 'n_estimat...",0.692427,0.659405,0.698505,0.707874,0.739679,0.699578,0.025858,54

Тестовая выборка дала приемлимый резульата r2 = 0.74.

In [100]:
X_finish = pd.read_csv('test.csv')
Id = X_finish['Id']
X_finish.drop(['Id', 'Healthcare_1', 'LifeSquare'], axis=1, inplace=True)
X_finish = pd.get_dummies(X_finish)
X_finish

,DistrictId,Rooms,Square,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Social_1,Social_2,Social_3,Helthcare_2,Shops_1,Ecology_2_A,Ecology_2_B,Ecology_3_A,Ecology_3_B,Shops_2_A,Shops_2_B
0,58,2.0,49.882643,6.0,6,14.0,1972,0.310199,11,2748,1,0,0,0,1,0,1,0,1
1,74,2.0,69.263183,1.0,6,1.0,1977,0.075779,6,1437,3,0,2,0,1,0,1,0,1
2,190,1.0,13.597819,12.0,2,5.0,1909,0.000000,30,7538,87,5,5,0,1,0,1,0,1
3,47,2.0,73.046609,9.0,22,22.0,2007,0.101872,23,4583,3,3,3,0,1,0,1,0,1
4,27,1.0,47.527111,1.0,17,17.0,2017,0.072158,2,629,1,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,11,3.0,67.133911,6.0,5,9.0,1973,0.000170,36,5992,0,1,1,0,1,0,1,0,1
4996,1,1.0,40.198472,10.0,12,17.0,2017,0.007122,1,264,0,0,1,0,1,0,1,0,1
4997,12,3.0,77.842178,9.0,23,22.0,1989,0.090799,74,19083,2,5,15,0,1,0,1,0,1
4998,62,2.0,81.305222,0.0,4,0.0,1977,0.072158,2,629,1,0,0,0,1,0,1,1,0
4999,30,2.0,60.555693,1.0,10,17.0,1977,0.000078,22,6398,141,3,23,0,1,0,1,0,1

In [101]:
finish_pred = rgr.predict(X_finish)

In [108]:
predict_prices = pd.DataFrame({'Id' : Id, 'Price': finish_pred})
predict_prices

         Id          Price
0       725  171557.227258
1     15856  219001.690278
2      5480  233627.099163
3     15664  348877.618726
4     14275  138892.959379
...     ...            ...
4995   8180  243342.102610
4996   4695  134472.723156
4997   5783  322447.080623
4998   4780  199739.966179
4999  12504  176485.333358

[5000 rows x 2 columns]

In [109]:
predict_prices.to_csv('finish_predict_prices', index=False)